### PR TITLE
fix: fixed issue with wrong execute directory on generate sdk stage #197

### PR DESCRIPTION
**Pull request by karandashovrz**
affects: @haulmont/jmix-front-generator

### CODE REVIEW

**Comment by vyacheslav-pushkin** [comment]
To keep discussions in one place:

> As for the deriveTemplate, its has process.cwd() call, but its used to set directory for projectModel export of existing jmix project (if model was out in options but we have answers), so this code is safe.

Why do we need to do it second time on `deriveTemplate` stage if it has already been done on `getProjectModel` stage? (`defaultGetProjectModel.tsx:49`).

> If we keep it inside methods (especially asynchronous) it doesn't guarantee that value of invocationDir will be correct at call moment.

I don't think that's true. `const invocationDir = process.cwd();` will execute before any stage will have a chance to run.

**Comment by vyacheslav-pushkin** [comment]
I think we need to refactor the SDK generator to use the new approach: get rid of `composeWith` and replace it with functions composition we use elsewhere. 

This will allow us not to repeat obtaining the project model twice (once for `app` and once for `sdk`). Instead there will be a single `getProjectModel` stage. Then on the `write` stage of the `app` generator we can reuse the `write` functions from `sdk` generator.

**Review by vyacheslav-pushkin — CHANGES_REQUESTED** [review]
See comments

**Comment by karandashovrz** [comment]
@vyacheslav-pushkin 

> Why do we need to do it second time on deriveTemplate stage if it has already been done on getProjectModel stage? (defaultGetProjectModel.tsx:49).

That is true. We can remove this code block from `deriveTemplate` stage.

> I don't think that's true. const invocationDir = process.cwd(); will execute before any stage will have a chance to run.

Yes, but `generate` is async function. I think is possible, when we have some several async calls in tasks queue, and some functional call can change cwd before `process.cwd()` will be called in `generate`, and we will get wrong cwd dir at generate call moment already.

**Review by web-devel — APPROVED** [review]

**Review by vyacheslav-pushkin — APPROVED** [review]

**Pull request merged**
