### PR TITLE
refactor: update jmix icons

### PR DESCRIPTION
**Pull request by HegelPro**
affects: @haulmont/jmix-front-generator

delete .png jmix icons and insert .svg jmix icons

[login](https://gyazo.com/fb190e3f4d15062139c6598e59f3acc9)
[header](https://gyazo.com/31fa36f5587d81f9b14ed4dfee87cd19)
[site icon](https://gyazo.com/054b171883c551a66e91c6c5bef352cb)

### CODE REVIEW

**Comment by vyacheslav-pushkin** [comment]
@HegelPro Please do not use `ISSUES CLOSED`. See `CONTRIBUTING.md` for details.

**Comment by HegelPro** [comment]
> @HegelPro Please do not use `ISSUES CLOSED`. See `CONTRIBUTING.md` for details.

ok

**Comment by vyacheslav-pushkin** [comment]
@HegelPro Could you please look into failing tests? (ignore Snyk for now, I think I know what's the problem)

Also, could you please add some screenshots to the PR?

**Comment by vyacheslav-pushkin** [comment]
I believe failing tests have nothing to do with this PR and can be fixed separately.

**Comment by HegelPro** [comment]
@vyacheslav-pushkin I think so. But i try to search an error. I think that the reason of fail e2e tests are problems with security `scr-jmix`.

**Comment by web-devel** [comment]
@HegelPro please rebase on master

**Review by web-devel — APPROVED** [review]

**Pull request merged**
